### ISSUE TITLE
Include only pages the user can see

### ISSUE THREAD

**Issue by gee72** [unidwell/confluence-include-child-pages-macro#3]
Pages that the user can't see are also included - they should be excluded, otherwise the include macro gives an error.

Wrap everything in the child page loop with:

```
#if($permissionHelper.canViewPage($action.getAuthenticatedUser(), $child.id))
...
...
#end
```

**Comment by unidwell** [comment]
Done 👍  Thank you for reporting the error.

The issue has been fixed in the last commit. Closing the issue as fixed (reopen it if needed).
